### ISSUE TITLE
htmlに、タイトル設定

### ISSUE THREAD

**Issue by CASIXx1** [HoriGit1st/Hori#1]
htmlファイルを作成し、
タイトルに適当な文字列を入れて下さい。

**Comment by CASIXx1** [comment]
```
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <title>Webサイトのタイトル</title>
    <meta name="description" content="ページの紹介文">
    <meta name="viewport" content="width=device-width, initial-scale=1">
 
<!-- CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.css">
    <link rel="stylesheet" href="css/style.css">
  </head>
 
  
  <body>
    <!-- ここにコンテンツが入ります -->
  </body>
</html>
```

**Comment by Hotatemaru** [comment]
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <title></title>
    <meta name="description" content="ページの紹介文">
    <meta name="viewport" content="width=device-width, initial-scale=1">
 

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.css">
    <link rel="stylesheet" href="css/style.css">
  </head>
 
  
  <body>
    
  </body>
</html>

**Comment by CASIXx1** [comment]
okでーす
